name: llm-develop
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hd77b12b_0
  - aiofiles=22.1.0=py311haa95532_0
  - aiohttp=3.8.5=py311h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py311haa95532_0
  - anyio=3.5.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h2bbff1b_0
  - arrow-cpp=11.0.0=ha81ea56_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py311haa95532_0
  - attrs=23.1.0=py311haa95532_0
  - aws-c-common=0.6.8=h2bbff1b_1
  - aws-c-event-stream=0.1.6=hd77b12b_6
  - aws-checksums=0.1.11=h2bbff1b_2
  - aws-sdk-cpp=1.8.185=hd77b12b_1
  - babel=2.11.0=py311haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.3.5=py311h5bb9823_0
  - brotli-python=1.0.9=py311hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2023.08.22=haa95532_0
  - certifi=2023.7.22=py311haa95532_0
  - cffi=1.15.1=py311h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.1.2=py311haa95532_0
  - cryptography=41.0.3=py311h89fc84f_0
  - datasets=2.12.0=py311haa95532_0
  - debugpy=1.6.7=py311hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.6=py311haa95532_0
  - entrypoints=0.4=py311haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fastapi=0.99.1=pyhd8ed1ab_0
  - filelock=3.9.0=py311haa95532_0
  - frozenlist=1.3.3=py311h2bbff1b_0
  - fsspec=2023.9.2=py311haa95532_0
  - gflags=2.2.2=ha925a31_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - glog=0.5.0=hd77b12b_0
  - greenlet=2.0.1=py311hd77b12b_0
  - grpc-cpp=1.48.2=hfe90ff0_1
  - h11=0.12.0=pyhd3eb1b0_0
  - huggingface_hub=0.17.3=py311haa95532_0
  - icu=58.2=ha925a31_3
  - idna=3.4=py311haa95532_0
  - importlib-metadata=6.0.0=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.0=py311h746a85d_0
  - ipython=8.15.0=py311haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311haa95532_0
  - jedi=0.18.1=py311haa95532_1
  - jinja2=3.1.2=py311haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py311haa95532_0
  - jupyter=1.0.0=py311haa95532_8
  - jupyter_client=7.4.9=py311haa95532_0
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.3.0=py311haa95532_0
  - jupyter_events=0.6.3=py311haa95532_0
  - jupyter_server=1.23.4=py311haa95532_0
  - jupyter_server_fileid=0.9.0=py311haa95532_0
  - jupyter_server_ydoc=0.8.0=py311haa95532_1
  - jupyter_ydoc=0.2.4=py311haa95532_0
  - jupyterlab=3.6.3=py311haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py311haa95532_0
  - jupyterlab_widgets=3.0.5=py311haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=8.1.1=h86230a5_0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=he2ea4bf_2
  - libthrift=0.15.0=h4364b78_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lxml=4.9.3=py311h09808a7_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py311h2bbff1b_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mistune=0.8.4=py311h2bbff1b_1000
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.8=py311h2bbff1b_0
  - mkl_random=1.2.4=py311h59b6b97_0
  - mpmath=1.3.0=py311haa95532_0
  - multidict=6.0.2=py311h2bbff1b_0
  - multiprocess=0.70.14=py311haa95532_0
  - nbclassic=0.5.5=py311haa95532_0
  - nbclient=0.5.13=py311haa95532_0
  - nbconvert=6.5.4=py311haa95532_0
  - nbformat=5.9.2=py311haa95532_0
  - nest-asyncio=1.5.6=py311haa95532_0
  - networkx=3.1=py311haa95532_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - notebook=6.5.4=py311haa95532_1
  - notebook-shim=0.2.2=py311haa95532_0
  - numexpr=2.8.7=py311h1fcbade_0
  - numpy=1.26.0=py311hdab7c0b_0
  - numpy-base=1.26.0=py311hd01c5d8_0
  - openssl=3.0.11=h2bbff1b_2
  - orc=1.7.4=h623e30f_1
  - packaging=23.1=py311haa95532_0
  - pandas=2.1.1=py311hf62ec03_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3=py311haa95532_0
  - platformdirs=3.10.0=py311haa95532_0
  - ply=3.11=py311haa95532_0
  - prometheus_client=0.14.1=py311haa95532_0
  - prompt-toolkit=3.0.36=py311haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py311h2bbff1b_0
  - psycopg2=2.9.3=py311h2bbff1b_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=11.0.0=py311h8a3a540_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py311h2bbff1b_1
  - pygments=2.15.1=py311haa95532_1
  - pyopenssl=23.2.0=py311haa95532_0
  - pyqt=5.15.7=py311hd77b12b_0
  - pyqt5-sip=12.11.0=py311hd77b12b_0
  - pyrsistent=0.18.0=py311h2bbff1b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311haa95532_0
  - python-json-logger=2.0.7=py311haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h2bbff1b_1
  - pytorch=2.0.1=cpu_py311hd080823_0
  - pytz=2023.3.post1=py311haa95532_0
  - pywin32=305=py311h2bbff1b_0
  - pywinpty=2.0.10=py311h5da7b33_0
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=23.2.0=py311hd77b12b_0
  - qt-main=5.15.2=h879a1e9_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtconsole=5.4.2=py311haa95532_0
  - qtpy=2.2.0=py311haa95532_0
  - qtwebkit=5.212=h2bbfb41_5
  - re2=2022.04.01=hd77b12b_0
  - regex=2023.10.3=py311h2bbff1b_0
  - requests=2.31.0=py311haa95532_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - safetensors=0.4.0=py311hcbdf901_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py311haa95532_0
  - sip=6.6.2=py311hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py311haa95532_1
  - soupsieve=2.5=py311haa95532_0
  - sqlalchemy=2.0.21=py311h2bbff1b_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - sympy=1.11.1=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py311haa95532_0
  - tinycss2=1.2.1=py311haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tokenizers=0.13.3=py311h49fca51_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.3.3=py311h2bbff1b_0
  - tqdm=4.65.0=py311h746a85d_0
  - traitlets=5.7.1=py311haa95532_0
  - transformers=4.32.1=py311haa95532_0
  - typing-extensions=4.7.1=py311haa95532_0
  - typing_extensions=4.7.1=py311haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py311haa95532_0
  - utf8proc=2.6.1=h2bbff1b_0
  - uvicorn=0.20.0=py311haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=0.58.0=py311haa95532_4
  - wheel=0.41.2=py311haa95532_0
  - widgetsnbextension=4.0.5=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winpty=0.4.3=4
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.4.2=h8cc25b3_0
  - y-py=0.5.9=py311hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - yarl=1.8.1=py311h2bbff1b_0
  - ypy-websocket=0.8.2=py311haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py311haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
prefix: C:\Users\Weihao Luo\.conda\envs\llm-develop
